# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Gotenberg path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ gotenberg_uid }}"
    group: "{{ gotenberg_gid }}"
  with_items:
    - "{{ gotenberg_base_path }}"

- name: Ensure Gotenberg support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ gotenberg_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ gotenberg_uid }}"
    group: "{{ gotenberg_gid }}"
  with_items:
    - env
    - labels
  register: gotenberg_support_files_result

- name: Ensure Gotenberg container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ gotenberg_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ gotenberg_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else gotenberg_container_image_force_pull }}"
  register: gotenberg_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: gotenberg_container_image_pull_result_ansible_module is not failed

- name: Ensure Gotenberg container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ gotenberg_container_image }}"
  register: gotenberg_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: gotenberg_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in gotenberg_container_image_pull_result_command.stdout"

- name: Ensure Gotenberg container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ gotenberg_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: gotenberg_network_creation_result

- name: Ensure Gotenberg container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ gotenberg_container_network }}
  register: gotenberg_network_creation_result
  changed_when: gotenberg_network_creation_result.rc == 0
  failed_when: gotenberg_network_creation_result.rc != 0 and 'already exists' not in gotenberg_network_creation_result.stderr

- name: Ensure Gotenberg systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/gotenberg.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ gotenberg_identifier }}.service"
    mode: "0644"
  register: gotenberg_systemd_service_result

- name: Determine whether Gotenberg needs a restart
  ansible.builtin.set_fact:
    gotenberg_restart_necessary: >-
      {{
        gotenberg_support_files_result.changed | default(false)
        or gotenberg_systemd_service_result.changed | default(false)
        or gotenberg_container_image_pull_result_ansible_module.changed | default(false)
        or gotenberg_container_image_pull_result_command.changed | default(false)
      }}
