# SPDX-FileCopyrightText: 2023, 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Gotenberg systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gotenberg_identifier }}.service"
  register: gotenberg_service_stat

- name: Uninstall Gotenberg systemd services and files
  when: gotenberg_service_stat.stat.exists | bool
  block:
    - name: Ensure Gotenberg systemd service is stopped
      ansible.builtin.service:
        name: "{{ gotenberg_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Gotenberg systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gotenberg_identifier }}.service"
        state: absent

    - name: Ensure Gotenberg container network does not exist
      when: gotenberg_container_network_deletion_enabled
      block:
        - name: Ensure Gotenberg container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ gotenberg_container_network }}"
            state: absent
          register: gotenberg_network_deletion_result

        - name: Ensure Gotenberg container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ gotenberg_container_network }}
          register: gotenberg_network_deletion_result
          changed_when: gotenberg_container_network in gotenberg_network_deletion_result.stdout

    - name: Ensure Gotenberg path does not exist
      ansible.builtin.file:
        path: "{{ gotenberg_base_path }}"
        state: absent
